In [2]:
import numpy as np
import tensorflow as tf
import torch

# Inverse Matrix

# Matrix Multiplication

We will cover the comparison of doing matrix multiplication using:
* Numpy
* TensorFlow
* PyTorch

The Multiplication for the Matrix are classified as follows:
- Matrix mult with Vector
- Matrix-Matrix Multiplication

-------------------------------------------------------------------
1. Multiply matrix with vector:

A = [[8, 2], [11, 6], [14, 3]]

b = [[9],[4]]

note that for `Numpy`, there is no particular Matrix to Vector multiplication, we use `np.dot()` to multiply it, with changing b into 1x2 vector from 2x1.

In [3]:
A = np.array([[8, 2], [11, 6], [14, 3]])
A

array([[ 8,  2],
       [11,  6],
       [14,  3]])

In [9]:
b = np.array([9,4])
b

array([9, 4])

In [10]:
np.dot(A, b)

array([ 80, 123, 138])

### Using `PyTorch`

In [12]:
A_pt = torch.tensor([[8, 2], [11, 6], [14, 3]])
A_pt

tensor([[ 8,  2],
        [11,  6],
        [14,  3]])

In [14]:
b_pt = torch.tensor([9,4])
b_pt

tensor([9, 4])

In [15]:
# Multiplication
torch.matmul(A_pt, b_pt)

tensor([ 80, 123, 138])

### Using `TensorFlow`

In [17]:
A_tf = tf.Variable([[8, 2], [11, 6], [14, 3]])
A_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[ 8,  2],
       [11,  6],
       [14,  3]])>

In [20]:
b_tf = tf.Variable([9,4])
b_tf

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 4])>

In [21]:
tf.linalg.matvec(A_tf, b_tf)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 80, 123, 138])>

2. Multiplication `Matrix` by `Matrix`

A = [[8, 2], [11, 6], [14, 3]]

B = [[9, 7],[4, 5]]

> Important Note:
> Matrix multiplication is not 'commutative', means AB /= BA. 

In [23]:
# Using A assigned with numpy above
A

array([[ 8,  2],
       [11,  6],
       [14,  3]])

In [26]:
# Create 2x2 matrix named 'B'
B = np.array([[9, 7],[4, 5]])
B

array([[9, 7],
       [4, 5]])

In [27]:
np.dot(A,B)

array([[ 80,  66],
       [123, 107],
       [138, 113]])

In [29]:
#np.dot(B,A) # This code will generate error, check the important note above

In [50]:
# A_pt is taken from above
B_pt = torch.from_numpy(B)

In [54]:
B_pt = torch.tensor([[9, 7],[4, 5]])
B_pt

tensor([[9, 7],
        [4, 5]])

In [55]:
torch.matmul(A_pt, B_pt) # same function, TensorFlow has different function

tensor([[ 80,  66],
        [123, 107],
        [138, 113]])

In [45]:
type(B_pt)

torch.Tensor

### Using `TensorFlow`

In [48]:
# A_tf is taken from A_tf above
B_tf = tf.convert_to_tensor(B, dtype=tf.int32)
B_tf

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[9, 7],
       [4, 5]])>

In [56]:
tf.matmul(A_tf, B_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 80,  66],
       [123, 107],
       [138, 113]])>

In [ ]:
# Symmetric and Identity Matrices

1. Symmetric Matrices is: 
    * square; 
    * X^T = X; 

In [59]:
X_sym = np.array([[0, 1, 2],[1, 3, 4], [2, 4, 5]])
X_sym

array([[0, 1, 2],
       [1, 3, 4],
       [2, 4, 5]])

In [60]:
X_sym.T

array([[0, 1, 2],
       [1, 3, 4],
       [2, 4, 5]])

In [61]:
X_sym.T == X_sym

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# Identity Matrix

Identity Matrix simply a symmetric matrix which has following properties:

* Every element along main diagonal is 1;
* All other elements are 0;
* Notation: ___In___ where n = height (width);
* n-length vector unchaged if multiplied by  ___In___

In [65]:
X_In = torch.tensor([[1,0, 0],[0,1,0],[0,0,1]])
X_In

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [70]:
x_pt = torch.tensor([[16], [27], [74]])
x_pt

tensor([[16],
        [27],
        [74]])

In [71]:
torch.matmul(X_In, x_pt)

tensor([[16],
        [27],
        [74]])

In [74]:
X_In_np = np.array([[1,0, 0],[0,1,0],[0,0,1]])
X_In_np

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [79]:
x_np = np.array([[16], [27], [74]])
x_np

array([[16],
       [27],
       [74]])

In [80]:
np.dot(X_In_np, x_np)

array([[16],
       [27],
       [74]])

# Exercises

In [82]:
A_np = np.array([[0,1,2],[3,4,5],[6,7,8]])
A_np

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
B_np = np.array([[-1],[1],[-2]])
B_np

array([[-1],
       [ 1],
       [-2]])

In [86]:
np.dot(A_np, B_np)

array([[ -3],
       [ -9],
       [-15]])

In [87]:
C_np = np.array([[-1,0],[1,1],[-2,2]])
C_np

array([[-1,  0],
       [ 1,  1],
       [-2,  2]])

In [88]:
np.dot(A_np, C_np)

array([[ -3,   5],
       [ -9,  14],
       [-15,  23]])

# 5.5 Linear Algebra in Machine Learning Application

Note:
Let say,

> a = house average price;

> b = property 1 (for instance, distance to school);

> c = property 2 (for instance, distance to hospital);

> . ;

> . ;

> . ;

> m
    

# Ch. 6 Special Matrices

Norm is basically used to measure the distance from the origin (0,0)


['Theory of Norm Youtube:'](https://www.youtube.com/watch?v=5fN2J8wYnfw)

['Norm in Machine Learning'](https://www.youtube.com/watch?v=FiSy6zWDfiA)


## 6.1 The Frobenius Norm (Eucledian Distance)



In [3]:
# make 2x2 matrix
x = np.array([[7,8], [9,10]])
x

array([[ 7,  8],
       [ 9, 10]])

In [4]:
# Calculate the Frobenius Norm of this matrix manually
(x[0,0]**2 + x[0,1]**2 + x[1,0]**2 + x[1,1]**2)**(1/2)

17.146428199482248

In [5]:
np.linalg.norm(x) #using function vector L2 norm; the result is the same

17.146428199482248

In [6]:
# USing PyTorch
x_pt = torch.tensor([[7,8], [9,10.]]) # torch.norm() MUST use floats (assign only one)
x_pt

tensor([[ 7.,  8.],
        [ 9., 10.]])

In [7]:
torch.norm(x_pt)

tensor(17.1464)

In [8]:
# Using TensorFlow
x_tf = tf.Variable([[7,8], [9,10.]]) # tf.norm() MUST use floats (assign only one)
x_tf

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 7.,  8.],
       [ 9., 10.]], dtype=float32)>

In [9]:
tf.norm(x_tf)

<tf.Tensor: shape=(), dtype=float32, numpy=17.14643>

## 6.2 Matrix Inversion

Matrix Inverse of X is denoted as $ X^(-1) $