This notebook contains:
* eigenvectors and eigenvalues
* determinants


In [3]:

import numpy as np
import torch
import matplotlib.pyplot as plt
%matplotlib inline

  Using cached torch-1.7.1-cp38-cp38-win_amd64.whl (184.0 MB)


In [2]:
v = np.array([3, 1])
v

array([3, 1])

Let's plot $v$ using my `plot_vectors()` function (which is based on Hadrien Jean's `plotVectors()` function from [this notebook](https://github.com/hadrienj/deepLearningBook-Notes/blob/master/2.7%20Eigendecomposition/2.7%20Eigendecomposition.ipynb), under [MIT license](https://github.com/hadrienj/deepLearningBook-Notes/blob/master/LICENSE)).

In [3]:
def plot_vectors(vectors, colors):
    """
    Plot one or more vectors in a 2D plane, specifying a color for each. 

    Arguments
    ---------
    vectors: list of lists or of arrays
        Coordinates of the vectors to plot. For example, [[1, 3], [2, 2]] 
        contains two vectors to plot, [1, 3] and [2, 2].
    colors: list
        Colors of the vectors. For instance: ['red', 'blue'] will display the
        first vector in red and the second in blue.
        
    Example
    -------
    plot_vectors([[1, 3], [2, 2]], ['red', 'blue'])
    plt.xlim(-1, 4)
    plt.ylim(-1, 4)
    """
    plt.figure()
    plt.axvline(x=0, color='lightgray')
    plt.axhline(y=0, color='lightgray')

    for i in range(len(vectors)):
        x = np.concatenate([[0,0],vectors[i]])
        plt.quiver([x[0]], [x[1]], [x[2]], [x[3]],
                   angles='xy', scale_units='xy', scale=1, color=colors[i],)

In [ ]:
plot_vectors([v], ['lightblue'])
_ = plt.xlim(-1, 5)
_ = plt.ylim(-1, 5)

## Exercises - Determinant

In [5]:
A = np.array([[25, 2], [3, 4]])
A

array([[25,  2],
       [ 3,  4]])

In [6]:
np.linalg.det(A)

94.0

In [7]:
B = np.array([[-2, 0], [0, -2]])
B

array([[-2,  0],
       [ 0, -2]])

In [8]:
np.linalg.det(B)

4.0

In [9]:
C = np.array([[2,1,-3], [4,-5,2], [0,-1,3]])
C

array([[ 2,  1, -3],
       [ 4, -5,  2],
       [ 0, -1,  3]])

In [10]:
np.linalg.det(C)

-26.000000000000014